# Site settings
title: No TV and No Beer
header-img: img/pineapple_farm.jpg
email: mikelui@drexel.edu
copyright_name: Mike Lui
description: "Experiences in the digital world and sometimes the real world, too"
baseurl: ""
url: "http://mikelui.io"
# twitter_username: SBootstrap
github_username:  mikelui
# facebook_username:  StartBootstrap
email_username:  mikelui@drexel.edu
linkedin_username: mikelui

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
